language: node_js
node_js:
  - "6"
  
script:
  - npm install
  - npm install surge -g
  - node_modules/.bin/gitbook install
  - node_modules/.bin/gitbook build
  - node_modules/.bin/surge --domain http://microservices-presentation.surge.sh/ --project ./_book